# Generated by Django 2.2.5 on 2019-12-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipedata',
            name='typ',
            field=models.CharField(default='lunch', max_length=200),
        ),
    ]
