# Generated by Django 2.2.5 on 2019-12-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipedata_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipedata',
            name='image',
            field=models.ImageField(default='recipe-images/none/noimg.jpg', upload_to='recipe-images/'),
        ),
    ]
