# Generated by Django 2.2 on 2019-12-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://ultkitchen.ca/wp-content/uploads/2018/08/food-image-placeholder.png', max_length=500),
        ),
    ]
